db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: amt_project
  ports:
    - "3306:3306"
  volumes:
    - ./db:/docker-entrypoint-initdb.d

backend:
  image: glassfish:latest
  ports:
    - "9876:8080"
  volumes:
  - ./Gamification-WP1.war:/usr/local/glassfish4/glassfish/domains/domain1/autodeploy/Gamification-WP1.war
  links:
    - db