version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: amt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amt_project
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysqld.cnf:/etc/mysql/conf.d/mysql.cnf
    command: --default-authentication-plugin=mysql_native_password
  payara:
    build: ./payara5
    volumes:
    - ./../target/:/opt/payara5/deployments/
    ports:
    - "9090:8080"
    - "9898:4848"
    links:
    - mysql:db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - "48888:80"
    links:
    - mysql:db