version: '3'
services:
  mysql:
    build: ./mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=amt_project
    - MYSQL_PASSWORD=root
    ports:
    - "3306:3306"
  payara:
    build: ./payara5
    volumes:
    - ./../target/:/opt/payara5/deployments/
    ports:
    - "8080:8080"
    - "4848:4848"
    links:
    - mysql:db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - "8888:80"
    links:
    - mysql:db